{
 "title": "jPowerMonitor Dashboard for filtered methods",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CO2 consumption top 5",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum by(method) (jPowerMonitor_co2_per_method_filtered{job=~\"jPowerMonitor\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max 5 energy consuming methods (filtered)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum by(method) (jPowerMonitor_energy_per_method_filtered{job=~\"jPowerMonitor\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power per method (filtered)",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 19, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "jPowerMonitor_power_per_method_filtered",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}